- name: living
  nightOnly: true
  illuminance_threshold: 600
  devices:
    - type: motion sensor
      statusTopic: "moreillon/light-d084cb/motion"
    - type: illuminance sensor
      statusTopic: "moreillon/light-d084cb/illuminance"
    - type: light
      commandTopic: "moreillon/light-d084cb/command"

- name: kitchen
  nightOnly: true
  illuminance_threshold: 850
  devices:
    # - type: motion sensor
    #   statusTopic: motion/kitchen/status
    - type: motion sensor
      statusTopic: /moreillon/light-a4c2f0/motion
    - type: illuminance sensor
      statusTopic: /moreillon/light-a4c2f0/illuminance
    - type: light
      commandTopic: /moreillon/light-a4c2f0/command
    - type: ac
      commandTopic: ac/kitchen/command

- name: corridor
  devices:
    # Motion sensors
    - type: motion sensor
      statusTopic: /moreillon/sensor-35a229/motion
    - type: motion sensor
      statusTopic: moreillon/sensor-35f3f0/motion # bathroom
    - type: motion sensor
      statusTopic: moreillon/sensor-db122f/motion # entrance
    # Lights
    - type: light
      commandTopic: "moreillon/light-2418e1/command"
    - type: light
      commandTopic: "/moreillon/light-d13efb/command"
    - type: light
      commandTopic: "/moreillon/light-c64739/command"
    # - type: light
    #   commandTopic: "moreillon/light-c75e4a/command" # Toilet

- name: toilet
  devices:
    - type: motion sensor
      statusTopic: moreillon/sensor-d920e7/motion
    - type: light
      commandTopic: moreillon/light-c75e4a/command # Toilet

- name: bedroom
  nightOnly: true
  devices:
    - type: motion sensor
      statusTopic: "motion/bedroom/status"
    - type: illuminance sensor
      statusTopic: /moreillon/light-a4d3d9/illuminance
    - type: light
      commandTopic: /moreillon/light-a4d3d9/command
    - type: ac
      commandTopic: ac/bedroom/command
